### PR TITLE
Refactorize the code with new OCaml tools

### PR DESCRIPTION
**Pull request by dannywillems**
Not sure about the module name.

### CODE REVIEW

**Comment by jrochel** [comment]
@dannywillems Hi there! Do you want to merge maybe? It would help us with extending the module.

**Comment by dannywillems** [comment]
> @dannywillems Hi there! Do you want to merge maybe? It would help us with extending the module.

Hi @jrochel. I was waiting for an answer from your side [here](https://github.com/dannywillems/ocaml-cordova-plugin-inappbrowser/pull/2#issuecomment-825043322). If you answer negatively, I can build on my side the example app https://github.com/dannywillems/ocaml-cordova-plugin-inappbrowser-example. It is fine to do it on my side, but as it has been a long time I didn't work on mobile apps, I will need to setup the environment on my machine. Let me know.

**Comment by jrochel** [comment]
@dannywillems This PR does not seem to have any backwards compatibility issues according to our tests.

**Comment by dannywillems** [comment]
Perfect, thanks for testing! Merging then.

**Pull request merged**
